services:
  pg:
    image: postgres:16
    container_name: pg-sports
    restart: unless-stopped
    environment:
      POSTGRES_USER: sports_user
      POSTGRES_PASSWORD: TuPassFuerte123
      POSTGRES_DB: sports_booking
    ports:
      - "5432:5432"
    volumes:
      - pgdata_sports:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin-sports
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: TuPassFuerte123
    ports:
      - "5050:80"
    depends_on:
      - pg

volumes:
  pgdata_sports:
